name: Artillery-Fargate-AWS-CodeBuild

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to check out"
        type: string
        required: true
        default: 'main'
      artillery_yml:
        description: "Artillery YML file"
        type: string
        required: true
        default: '<filename.yml>'
      testName:
        description: "Uniuque Test Name"
        type: string
        required: true
        default: 'playwright-load-test-1'
      serviceName:
        description: "Service Name to group all the executions for opentelemetry"
        type: string
        required: true
        default: 'playwright-dev-tests'
      metrics_url:
        description: "Metrics and Opentelemetry URL"
        type: string
        required: true
        default: ''
      parallel_browsers:
        description: "No. of Parallel Browser instances on AWS Fargate"
        type: number
        required: true
        default: 1

permissions:
  id-token: write
  contents: read

jobs:
  artillery:
    runs-on: codebuild-artillery-performance-17-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: '${{ inputs.branch }}'

      - name: Run Fargate Test
        timeout-minutes: 15 # best practice: adding timeout in case something goes wrong with the test, so that GitHub Action won’t run for the default 6h
        run: |
          run run-fargate --region us-east-1 --count ${{ inputs.parallel_browsers }} --cpu 1024 --memory 2048 --output "${{ inputs.testName }}"-results.json --cluster artillery-opentelemetry-metrics --variables '{ "test_name": "${{ inputs.testName }}", "service_name": "${{ inputs.serviceName }}", "metrics_url": "${{ inputs.metrics_url }}" }' ./${{ inputs.artillery_yml }}
          # --record --key ${{ secrets.ARTILLERY_RESULTS_KEY }}
          aws s3api create-bucket --bucket artilleryio-results 
          aws s3 cp "${{ inputs.testName }}"-results.json s3://artilleryio-results/"${{ inputs.testName }}"-results.json
          run report "${{ inputs.testName }}"-results.json
          aws s3 cp "${{ inputs.testName }}"-results.json.html s3://artilleryio-results/"${{ inputs.testName }}"-results.html
