name: Artillery-Fargate-AWS-CodeBuild

on:
  workflow_dispatch:

permissions:
  contents: read #this is needed so that checkout of repository can happen

jobs:
  artillery:
    runs-on: codebuild-artillery-fargare-poc-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Fargate Test
        uses: artilleryio/action-cli@v1
        timeout-minutes: 60 # best practice: adding timeout in case something goes wrong with the test, so that GitHub Action won’t run for the default 6h
        with:
          command: run-fargate --region us-east-1 --count 1 --cpu 1024 --memory 2048 ./browser-load-test.yml --record --key ${{ secrets.ARTILLERY_RESULTS_KEY }}
