name: Artillery-Fargate-AWS-CodeBuild

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to check out"
        type: string
        required: true
        default: 'main'
      artillery_yml:
        description: "Artillery YML file"
        type: string
        required: true
        default: '<filename.yml>'

permissions:
  id-token: write
  contents: read

jobs:
  artillery:
    runs-on: codebuild-artillery-qa-performance-2-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: '${{ inputs.branch }}'

      - name: Run Fargate Test
        timeout-minutes: 15 # best practice: adding timeout in case something goes wrong with the test, so that GitHub Action won’t run for the default 6h
        run: |
          run run-fargate --region us-east-1 --count 1 --cpu 1024 --memory 2048 ./${{ inputs.artillery_yml }} --record --key ${{ secrets.ARTILLERY_RESULTS_KEY }}
