name: Artillery-Fargate-AWS-CodeBuild

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  artillery:
    runs-on: codebuild-actions-github-personal-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::058264331455:role/github-oidc-personal
          aws-region: us-east-1
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Fargate Test
        uses: artilleryio/action-cli@v1
        timeout-minutes: 15 # best practice: adding timeout in case something goes wrong with the test, so that GitHub Action won’t run for the default 6h
        with:
          command: run-fargate --region us-east-1 --count 1 --cpu 1024 --memory 2048 ./browser-test-with-steps.yml --record --key ${{ secrets.ARTILLERY_RESULTS_KEY }}
