name: Artillery-Fargate-AWS-AccessKey-Ubuntu-Runner

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to check out"
        type: string
        required: true
        default: 'main'
      artillery_yml:
        description: "Artillery YML file"
        type: string
        required: true
        default: '<filename.yml>'
      testName:
        description: "Uniuque Test Name"
        type: string
        required: true
        default: 'playwright-load-test-1'
      serviceName:
        description: "Service Name to group all the executions for opentelemetry"
        type: string
        required: true
        default: 'playwright-dev-tests'
      metrics_url:
        description: "Metrics and Opentelemetry URL"
        type: string
        required: true
        default: ''
permissions:
  contents: read #this is needed so that checkout of repository can happen

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Fargate Test
        uses: artilleryio/action-cli@v1
        timeout-minutes: 60 # best practice: adding timeout in case something goes wrong with the test, so that GitHub Action won’t run for the default 6h
        with:
          command: run-fargate --region us-east-1 --count 3 --cpu 1024 --memory 2048 --cluster artillery-opentelemetry-metrics --variables '{ "test_name":"${{ inputs.testName }}","service_name":"${{ inputs.serviceName }}","metrics_url":"${{ inputs.metrics_url }}" }' ./${{ inputs.artillery_yml }} --record --key ${{ secrets.ARTILLERY_RESULTS_KEY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
